# Generated by Django 4.0.5 on 2022-06-06 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='notebook',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notesnippet',
            name='notebook_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_snippets', to='notebook.notebook'),
        ),
    ]
