# Generated by Django 4.0.5 on 2022-06-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_remove_notebook_owner_id_notebook_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
